apiVersion: v1
kind: ServiceAccount
metadata:
  name: "187"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: "187"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "187"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "187"
subjects:
- kind: ServiceAccount
  name: "187"
  namespace: "default"
---
