apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: cert-manager
  version: 1.0.0

resources:
- deployment.yaml
- rbac.yaml
- crd.yaml
- service.yaml
- tls.yaml

generatorOptions:
  disableNameSuffixHash: true
